[project]
name = "eyelab"
version = "0.4.2"
description = "Multi-modal annotation tool for eye imaging data"
authors = [{ name = "Olivier Morelle", email = "oli4morelle@gmail.com" }]
requires-python = ">=3.12"
license = "MIT"
dependencies = [
    "eyepy>=0.18.1",
    "imagecodecs>=2025.8.2",
    "pyside6>=6.10.0",
    "qimage2ndarray>=1.10.0",
    "requests>=2.32.5",
]

[project.scripts]
eyelab = "eyelab.main:main"

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "commitizen>=4.9.1",
    "pyinstaller>=6.16.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "pytest-qt>=4.5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.semantic_release]
major_on_zero = false
version_variable = ['eyelab/__init__.py:__version__']
version_toml = "pyproject.toml:project.version"
version_pattern = ["CITATION.cff:v(\\d+\\.\\d+\\.\\d+)", "README.md:v(\\d+\\.\\d+\\.\\d+)"]
upload_to_pypi = true
upload_to_release = true
build_command = "uv build"
branch = "main"
