name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Quality:
    uses: MedVisBonn/eyelab/.github/workflows/_quality.yaml@master

  Release:
    needs: Quality
    uses: MedVisBonn/eyelab/.github/workflows/_release.yaml@master
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
